import type { Metadata } from "next";
import { Urbanist } from "next/font/google";
import "@/styles/styles.scss";

const urbanist = Urbanist({
  subsets: ["latin"],
  variable: "--ff-default",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${urbanist.variable}`}>{children}</body>
    </html>
  );
}
